export default Object.freeze({
  LOGIN_STACK: 'LoginFlowStack',
  LOGIN_SCREEN: 'LoginScreen',
  LOGIN_HOME: 'LoginFlowHome',
  SINGUP_SCREEN: 'SignupScreen',
  SPLASH_SCREEN: 'SplashScreen',
  HOME_SCREEN: 'BottomTabs',
  PRODUCT_LIST_SCREEN: 'ProductListScreen',
  PRODUCT_DETAILS: 'ProductDetailsScreen',
  PROFILE_STACK: 'ProfileStack',
  PROFILE_SCREEN: 'ProfileHomeScreen',
  USER_INFO: 'UserInfoScreen',
  USER_ADDRESS: 'UserAddressScreen',
  USER_PURCHASES: 'UserPurchasesScreen',
  CART_STACK: 'CartStack',
  CART_SCREEN: 'CartScreen',
});
